/*****************************************************************************
*
* Copyright (c) 2000 - 2007, The Regents of the University of California
* Produced at the Lawrence Livermore National Laboratory
* All rights reserved.
*
* This file is part of VisIt. For details, see http://www.llnl.gov/visit/. The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or materials provided with the distribution.
*  - Neither the name of the UC/LLNL nor  the names of its contributors may be
*    used to  endorse or  promote products derived from  this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED.  IN  NO  EVENT  SHALL  THE  REGENTS  OF  THE  UNIVERSITY OF
* CALIFORNIA, THE U.S.  DEPARTMENT  OF  ENERGY OR CONTRIBUTORS BE  LIABLE  FOR
* ANY  DIRECT,  INDIRECT,  INCIDENTAL,  SPECIAL,  EXEMPLARY,  OR CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtLareV2FileFormat.C                           //
// ************************************************************************* //

#include <avtLareV2FileFormat.h>

#include <string>

#include <vtkFloatArray.h>
#include <vtkDoubleArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>

#include <avtDatabaseMetaData.h>

#include <Expression.h>

#include <InvalidVariableException.h>

#include <DebugStream.h>


using     std::string;

vtkDataArray* (avtLareV2FileFormat::*read_current)(int) = NULL;

//#define OFFSET 4*sizeof(int)+sizeoffloat+sizeoffloat*(dims[0]+dims[1]+dims[2])


// ****************************************************************************
//  Method: avtLareV2 constructor
//
//  Programmer: bradyc -- generated by xml2avt
//  Creation:   Thu May 17 09:41:55 PDT 2007
//
// ****************************************************************************

avtLareV2FileFormat::avtLareV2FileFormat(const char *filename)
    : avtSTSDFileFormat(filename)
{
  if (file.is_open()) file.close();
  file.open(filename);
  if (!file.good()) return;

  int flen;
  file.seekg(0,ios::end);
  flen=file.tellg();
  file.seekg(0,ios::beg);

  char end[10];
  memset(end,0,10);
  int stlen=strlen(filename);
  const char* filenamepoint = filename+stlen-9;
  strncpy(end,filenamepoint,9);
  debug1 << "Full filename " << filename << "\n";
  debug1 << "Recovered tag " << end << "\n";

  sscanf(end,"%i",&this->cycle);
  debug1 << "Cycle number " << this->cycle << "\n";

  file.read((char*)&this->dims,sizeof(int)*3);
  this->dims[0]++;
  this->dims[1]++;
  this->dims[2]++;
  file.read((char*)&this->sizeoffloat,sizeof(int));
  debug1 << this->sizeoffloat << endl;

  //This bit is a bodge to make the plugin backwards compatible
  //Remove when possible.
  if (this->sizeoffloat !=8 && this->sizeoffloat !=4)
    {
      this->sizeoffloat = PREC;
      offset=3*sizeof(int)+sizeoffloat+sizeoffloat*(dims[0]+dims[1]+dims[2]);
      file.seekg(-sizeof(int),ios::cur);
    }
  else // endbodge
    offset=4*sizeof(int)+sizeoffloat+sizeoffloat*(dims[0]+dims[1]+dims[2]);


  if (this->sizeoffloat == 8)
    {
      file.read((char*)&this->time,sizeoffloat);
    }
  else
    {
      float f;
      file.read((char*)&f,sizeoffloat);
      this->time=f;
    }


  debug1 << "Current time is " << this->time << "\n";
  debug1 << "ngrid is " << dims[0] << " x " << dims[1] << " x " << dims[2] << "\n";

  this->x=malloc(sizeoffloat*this->dims[0]);
  this->y=malloc(sizeoffloat*this->dims[1]);
  this->z=malloc(sizeoffloat*this->dims[2]);


  debug1 << "Reading X\n";
  file.read((char*)this->x,sizeoffloat*this->dims[0]);
  debug1 << "Reading Y\n";
  file.read((char*)this->y,sizeoffloat*this->dims[1]);
  debug1 << "Reading Z\n";
  file.read((char*)this->z,sizeoffloat*this->dims[2]);
  debug1 << "Read data, starting \n";

  if (sizeoffloat == 4)
    {
      read_current=&avtLareV2FileFormat::read_current_sgl;
    }
  else
    {
      read_current=&avtLareV2FileFormat::read_current_dbl;
    }

}


// ****************************************************************************
//  Method: avtLareV2FileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: bradyc -- generated by xml2avt
//  Creation:   Thu May 17 09:41:55 PDT 2007
//
// ****************************************************************************

void
avtLareV2FileFormat::FreeUpResources(void)
{
  /*  free(this->x);
  free(this->y);
  free(this->z);*/
  //file.close();
}


// ****************************************************************************
//  Method: avtLareV2FileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: bradyc -- generated by xml2avt
//  Creation:   Thu May 17 09:41:55 PDT 2007
//
// ****************************************************************************

void
avtLareV2FileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md)
{
  std::string meshname="Mesh";
  avtMeshMetaData *mmd= new avtMeshMetaData;
  mmd->name = meshname;
  mmd->spatialDimension = 3;
  mmd->topologicalDimension = 3;
  mmd->meshType = AVT_RECTILINEAR_MESH;
  mmd->numBlocks=1;
  md->Add(mmd);


    avtCentering cent = AVT_NODECENT;

    AddScalarVarToMetaData(md, "Fluid/Density", meshname, cent);
    AddScalarVarToMetaData(md, "Fluid/Energy", meshname, cent);
    AddScalarVarToMetaData(md, "Velocity/V_x", meshname, cent);
    AddScalarVarToMetaData(md, "Velocity/V_y", meshname, cent);
    AddScalarVarToMetaData(md, "Velocity/V_z", meshname, cent);
    AddScalarVarToMetaData(md, "Magnetic_Field/B_x", meshname, cent);
    AddScalarVarToMetaData(md, "Magnetic_Field/B_y", meshname, cent);
    AddScalarVarToMetaData(md, "Magnetic_Field/B_z", meshname, cent);
    AddScalarVarToMetaData(md, "Current/J_x",meshname,cent);
    AddScalarVarToMetaData(md, "Current/J_y",meshname,cent);
    AddScalarVarToMetaData(md, "Current/J_z",meshname,cent);


    Expression expr;
    expr.SetName("Velocity");
      expr.SetDefinition("{<Velocity/V_x>,<Velocity/V_y>,<Velocity/V_z>}");
    expr.SetType(Expression::VectorMeshVar);
    md->AddExpression(&expr);

    expr.SetName("Magnetic_Field");
      expr.SetDefinition("{<Magnetic_Field/B_x>,<Magnetic_Field/B_y>,<Magnetic_Field/B_z>}");
    expr.SetType(Expression::VectorMeshVar);
    md->AddExpression(&expr);

    expr.SetName("Velocity/|V|");
    expr.SetDefinition("sqrt(<Velocity/V_x>^2+<Velocity/V_y>^2+<Velocity/V_z>^2)");
    expr.SetType(Expression::ScalarMeshVar);
    md->AddExpression(&expr);

    expr.SetName("Magnetic_Field/|B|");
    expr.SetDefinition("sqrt(<Magnetic_Field/B_x>^2+<Magnetic_Field/B_y>^2+<Magnetic_Field/B_z>^2)");
    expr.SetType(Expression::ScalarMeshVar);
    md->AddExpression(&expr);

    expr.SetName("Fluid/Pressure");
    expr.SetDefinition("2.0/3.0 * <Fluid/Energy> * <Fluid/Density>");
    expr.SetType(Expression::ScalarMeshVar);
    md->AddExpression(&expr);
       

        expr.SetName("Current");
	expr.SetDefinition("{<Current/J_x>, <Current/J_y>, <Current/J_z>}");
	expr.SetType(Expression::VectorMeshVar);
	md->AddExpression(&expr);


        expr.SetName("Current/|J|");
        expr.SetDefinition("sqrt(<Current/J_x>^2 + <Current/J_y>^2 + <Current/J_z>^2)");
        expr.SetType(Expression::ScalarMeshVar);
	md->AddExpression(&expr);
}

// ****************************************************************************
//  Method: avtLareV2FileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: bradyc -- generated by xml2avt
//  Creation:   Thu May 17 09:41:55 PDT 2007
//
// ****************************************************************************

vtkDataSet *
avtLareV2FileFormat::GetMesh(const char *meshname)
{

      if (!this->x || !this->y || !this->z) return NULL;
      vtkDataArray *xx = NULL;
      vtkDataArray *yy = NULL;
      vtkDataArray *zz = NULL;

      if (sizeoffloat==4)
	{
	  xx=vtkFloatArray::New();
	  yy=vtkFloatArray::New();
	  zz=vtkFloatArray::New();
	  ((vtkFloatArray*)xx)->SetArray((float*)this->x,this->dims[0],1);
	  ((vtkFloatArray*)yy)->SetArray((float*)this->y,this->dims[1],1);
	  ((vtkFloatArray*)zz)->SetArray((float*)this->z,this->dims[2],1);
	}
      else
	{
	  xx=vtkDoubleArray::New();
	  yy=vtkDoubleArray::New();
	  zz=vtkDoubleArray::New();
	  ((vtkDoubleArray*)xx)->SetArray((double*)this->x,this->dims[0],1);
	  ((vtkDoubleArray*)yy)->SetArray((double*)this->y,this->dims[1],1);
	  ((vtkDoubleArray*)zz)->SetArray((double*)this->z,this->dims[2],1);
	}
      
      vtkRectilinearGrid *grid = vtkRectilinearGrid::New();

      grid->SetDimensions(this->dims);
      grid->SetXCoordinates(xx);
      grid->SetYCoordinates(yy);
      grid->SetZCoordinates(zz);

      xx->Delete();
      yy->Delete();
      zz->Delete();
      return grid;
}


// ****************************************************************************
//  Method: avtLareV2FileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: bradyc -- generated by xml2avt
//  Creation:   Thu May 17 09:41:55 PDT 2007
//
// ****************************************************************************

vtkDataArray *
avtLareV2FileFormat::GetVar(const char *varname)
{
  int offset=this->offset;

  if (!this->file.good()) return NULL;

  if (strcmp(varname,"Fluid/Density") == 0)
    offset+=0;
  else if (strcmp(varname,"Fluid/Energy") == 0)
    offset+=sizeoffloat*(dims[0]*dims[1]*dims[2]);
  else if (strcmp(varname,"Velocity/V_x")==0)
    offset+=2*sizeoffloat*(dims[0]*dims[1]*dims[2]);
  else if (strcmp(varname,"Velocity/V_y")==0)
    offset+=3*sizeoffloat*(dims[0]*dims[1]*dims[2]);
  else if (strcmp(varname,"Velocity/V_z")==0)
    offset+=4*sizeoffloat*(dims[0]*dims[1]*dims[2]);
  else if (strcmp(varname,"Magnetic_Field/B_x")==0)
    offset+=5*sizeoffloat*(dims[0]*dims[1]*dims[2]);
  else if (strcmp(varname,"Magnetic_Field/B_y")==0)
    offset+=6*sizeoffloat*(dims[0]*dims[1]*dims[2]);
  else if (strcmp(varname,"Magnetic_Field/B_z")==0)
    offset+=7*sizeoffloat*(dims[0]*dims[1]*dims[2]);
  else if (strcmp(varname,"Current/J_x")==0)
    return (*this.*read_current)(0);
  else if (strcmp(varname,"Current/J_y")==0)
    return (*this.*read_current)(1);
  else if (strcmp(varname,"Current/J_z")==0)
  return (*this.*read_current)(2);
  else
    EXCEPTION1(InvalidVariableException, varname);

  vtkDataArray *arr= NULL;

  if (this->sizeoffloat==4)
    {
      arr = vtkFloatArray::New();
    }
  else
    {
      arr = vtkDoubleArray::New();
    }
  if (!arr) return NULL;
  arr->SetNumberOfTuples(dims[0]*dims[1]*dims[2]);
  void* data = arr->GetVoidPointer(0);
  if (!data) return NULL;

  file.seekg(offset,ios::beg);
  file.read((char*)data,sizeoffloat*(dims[0]*dims[1]*dims[2]));

  return arr;

}


// ****************************************************************************
//  Method: avtLareV2FileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: bradyc -- generated by xml2avt
//  Creation:   Thu May 17 09:41:55 PDT 2007
//
// ****************************************************************************

vtkDataArray *
avtLareV2FileFormat::GetVectorVar(const char *varname)
{
  return NULL;
}

// ****************************************************************************
//  Method: avtLareV2FileFormat::read_current
//
//  Purpose:
//      Calculate the current using LARE like differentials
//      Still experimental
//
//
//  Arguments:
//      direction    <0=NULL,0=jx,1=jy,2=jz,>2=NULL
//
//
// ****************************************************************************
vtkDataArray *
avtLareV2FileFormat::read_current_sgl(int direction)
{
    if (direction < 0 || direction >2) return NULL;
  long ix,iy,iz,izo;
  long offset;
  float *B_Current,*x,*y,*z;
  x=(float*)this->x;
  y=(float*)this->y;
  z=(float*)this->z;
  vtkDataArray *arr=NULL;
  arr = vtkFloatArray::New();
  if (!arr) return NULL;
  arr->SetNumberOfTuples(dims[0]*dims[1]*dims[2]);
  float* data = (float*)arr->GetVoidPointer(0);
  if (!data) return NULL;
  memset(data,0,sizeoffloat*dims[0]*dims[1]*dims[2]);

  B_Current=(float*)malloc(sizeoffloat*dims[0]*dims[1]*dims[2]);

  switch(direction)
    {
    case 0:
      offset=this->offset+6*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBy/dz
	  if (range_check(ix,iy,iz))
	    data[i]+=(B_Current[i]-B_Current[xyzTOi(ix,iy,iz+1)])/(z[iz+1]-z[iz]);

	}
      offset=this->offset+7*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBz/dy
	  if (range_check(ix,iy,iz))
	  	  data[i]-=(B_Current[i]-B_Current[xyzTOi(ix,iy+1,iz)])/(y[iy+1]-y[iy]);
	}
      //Next loop simply moves the current to the cell vertices
      //If speed is crucial, simply rem this out
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //Move to vertices
	  if (range_check(ix,iy,iz))
	  	  {
		    data[i]+=data[xyzTOi(ix+1,iy,iz)];
		    data[i]/=2.0;
		  }
	}

	 break;

    case 1:
      offset=this->offset+5*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBx/dz
	  if (range_check(ix,iy,iz))
	    data[i]-=(B_Current[i]-B_Current[xyzTOi(ix,iy,iz+1)])/(z[iz+1]-z[iz]);

	}
      offset=this->offset+7*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBz/dx
	  if (range_check(ix,iy,iz))
	  	  data[i]+=(B_Current[i]-B_Current[xyzTOi(ix+1,iy,iz)])/(x[ix+1]-x[ix]);
	}
      //Next loop simply moves the current to the cell vertices
      //If speed is crucial, simply rem this out
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //Move to vertices
	  if (range_check(ix,iy,iz))
	  	  {
		    data[i]+=data[xyzTOi(ix,iy+1,iz)];
		    data[i]/=2.0;
		  }
	}

	 break;

    case 2:
      offset=this->offset+5*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBx/dy
	  if (range_check(ix,iy,iz))
	    data[i]+=(B_Current[i]-B_Current[xyzTOi(ix,iy+1,iz)])/(y[iy+1]-y[iy]);

	}
      offset=this->offset+6*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBy/dx
	  if (range_check(ix,iy,iz))
	  	  data[i]-=(B_Current[i]-B_Current[xyzTOi(ix+1,iy,iz)])/(x[ix+1]-x[ix]);
	}
      //Next loop simply moves the current to the cell vertices
      //If speed is crucial, simply rem this out
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //Move to vertices
	  if (range_check(ix,iy,iz))
	  	  {
		    data[i]+=data[xyzTOi(ix,iy,iz+1)];
		    data[i]/=2.0;
		  }
	}
	 break;

    default:
	   break;
    }
  free(B_Current);
  return arr;
}
// ****************************************************************************
vtkDataArray *
avtLareV2FileFormat::read_current_dbl(int direction)
{
    if (direction < 0 || direction >2) return NULL;
  long ix,iy,iz,izo;
  long offset;
  double *B_Current,*x,*y,*z;
  x=(double*)this->x;
  y=(double*)this->y;
  z=(double*)this->z;
  vtkDataArray *arr=NULL;
  arr = vtkDoubleArray::New();
  if (!arr) return NULL;
  arr->SetNumberOfTuples(dims[0]*dims[1]*dims[2]);
  double* data = (double*)arr->GetVoidPointer(0);
  if (!data) return NULL;
  memset(data,0,sizeoffloat*dims[0]*dims[1]*dims[2]);

  B_Current=(double*)malloc(sizeoffloat*dims[0]*dims[1]*dims[2]);

  switch(direction)
    {
    case 0:
      offset=this->offset+6*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBy/dz
	  if (range_check(ix,iy,iz))
	    data[i]+=(B_Current[i]-B_Current[xyzTOi(ix,iy,iz+1)])/(z[iz+1]-z[iz]);

	}
      offset=this->offset+7*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBz/dy
	  if (range_check(ix,iy,iz))
	  	  data[i]-=(B_Current[i]-B_Current[xyzTOi(ix,iy+1,iz)])/(y[iy+1]-y[iy]);
	}
      //Next loop simply moves the current to the cell vertices
      //If speed is crucial, simply rem this out
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //Move to vertices
	  if (range_check(ix,iy,iz))
	  	  {
		    data[i]+=data[xyzTOi(ix+1,iy,iz)];
		    data[i]/=2.0;
		  }
	}

	 break;

    case 1:
      offset=this->offset+5*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBx/dz
	  if (range_check(ix,iy,iz))
	    data[i]-=(B_Current[i]-B_Current[xyzTOi(ix,iy,iz+1)])/(z[iz+1]-z[iz]);

	}
      offset=this->offset+7*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBz/dx
	  if (range_check(ix,iy,iz))
	  	  data[i]+=(B_Current[i]-B_Current[xyzTOi(ix+1,iy,iz)])/(x[ix+1]-x[ix]);
	}
      //Next loop simply moves the current to the cell vertices
      //If speed is crucial, simply rem this out
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //Move to vertices
	  if (range_check(ix,iy,iz))
	  	  {
		    data[i]+=data[xyzTOi(ix,iy+1,iz)];
		    data[i]/=2.0;
		  }
	}

	 break;

    case 2:
      offset=this->offset+5*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBx/dy
	  if (range_check(ix,iy,iz))
	    data[i]+=(B_Current[i]-B_Current[xyzTOi(ix,iy+1,iz)])/(y[iy+1]-y[iy]);

	}
      offset=this->offset+6*sizeoffloat*(dims[0]*dims[1]*dims[2]);
      file.seekg(offset,ios::beg);
      file.read((char*)B_Current,sizeoffloat*(dims[0]*dims[1]*dims[2]));
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //dBy/dx
	  if (range_check(ix,iy,iz))
	  	  data[i]-=(B_Current[i]-B_Current[xyzTOi(ix+1,iy,iz)])/(x[ix+1]-x[ix]);
	}
      //Next loop simply moves the current to the cell vertices
      //If speed is crucial, simply rem this out
      for (long i=0;i<dims[0]*dims[1]*dims[2];++i)
	{
	  iTOxyz(i,&ix,&iy,&iz);
	  //Move to vertices
	  if (range_check(ix,iy,iz))
	  	  {
		    data[i]+=data[xyzTOi(ix,iy,iz+1)];
		    data[i]/=2.0;
		  }
	}
	 break;

    default:
	   break;
    }
  free(B_Current);
  return arr;
}
// ****************************************************************************
long avtLareV2FileFormat::xyzTOi(long ix, long iy, long iz)
{
  int i;
  i=iz*dims[0]*dims[1];
  i+=iy*dims[0];
  i+=ix;

  return i;
}
// ****************************************************************************
void avtLareV2FileFormat::iTOxyz(long i,long *ix, long *iy, long *iz)
{
*iz=i/(dims[0]*dims[1]);
*iy=(i-*iz*dims[0]*dims[1])/dims[0];
*ix=i-*iz*dims[0]*dims[1]-*iy*dims[0];
}
// ****************************************************************************
bool avtLareV2FileFormat::range_check(int ix,int iy,int iz)
{
  if (ix <0 || ix >= dims[0]-1) return false;
  if (iy <0 || iy >= dims[1]-1) return false;
  if (iz <0 || iz >= dims[2]-1) return false;
  return true;
}
